---
name: "CI"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"

jobs:
  compose-build-test:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Linting Code & Building Image"
        run: "docker compose build"
      - name: "Run Tests in Container"
        run: "docker compose run test"
