---
name: "CI"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

jobs:
  yamllint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: yamllint"
        run: "poetry run yamllint . -c .yamllint.yml"
  pytest:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Testing: pytest"
        run: "poetry run invoke tests"
  baked-cookies:
    needs:
      - "yamllint"
      - "pytest"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
      matrix:
        include:
          - template: "python"
            example: "baking-contest"
            build: true
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      # - name: "Running Baked Tests with --build"
      #   run: "poetry run invoke baked-test --example=${{ matrix.example }} --build"
      #   if: "matrix.build"
      # - name: "Running Baked Tests w/o --build"
      #   run: "poetry run invoke baked-test --example=${{ matrix.example }}"
      #   if: "!matrix.build"
